### ISSUE TITLE
Inform that they need to add http to acceptlist

### ISSUE THREAD

**Issue by nothingismagick** [persiliao/axios-tauri-api-adapter#2]
You should probably notify the user that they will need to enable the `http` feature in the API acceptlist of their `tauri.conf.json` file.

**Comment by persiliao** [comment]
Thanks, I think your proposal is very good, it will be more friendly for users who are just starting to use Tauri

**Comment by persiliao** [comment]
@nothingismagick It's already added to [README.md](https://github.com/persiliao/axios-tauri-api-adapter#usage)
