### ISSUE TITLE
[maybe a bug] this npm package only support pnpm?

### ISSUE THREAD

**Issue by yundove** [persiliao/axios-tauri-api-adapter#3]
hello. i have a question.

when i install this package using **npm** from [npm registry](https://www.npmjs.com/package/axios-tauri-api-adapter), get an error as below:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! axios-tauri-api-adapter@0.1.3 preinstall: `npx only-allow pnpm`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the axios-tauri-api-adapter@0.1.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\test\AppData\Roaming\npm-cache\_logs\2022-07-26T06_33_52_039Z-debug.log
```

look your package.json, maybe this causes.

https://github.com/persiliao/axios-tauri-api-adapter/blob/master/package.json#L30

why add this `preinstall`? please support npm && yarn, thank you. 

### info

- version: axios-tauri-api-adapter@0.1.3
- package manager: npm
- nodejs version: v14.18.3
- npm version: 6.14.15
- os: windows 10 (not use a wsl)

**Comment by persiliao** [comment]
Only PNPM is supported, and that's because it's development time, There are no restrictions when it is officially installed and used
