### ISSUE TITLE
default timeout is zero ms

### ISSUE THREAD

**Issue by dady8889** [persiliao/axios-tauri-api-adapter#30]
Hi,
so I started my first project with Tauri and Axios, and was perplexed for many hours by this simple issue.

If you do

```
axios.create({
          adapter: ...
})
```
the default `timeout:` is **zero**. Now, according to Axios [docs](https://github.com/axios/axios/blob/main/README.md#request-config), this is meant as **infinity**. But when this gets passed down in the config to Tauri `fetch`, it will actually mean that timeout is zero ms and of course, no request gets done in that time, so every request fails. It may be possible that this is default behaviour on Windows only, not sure. (Interestingly, the rust logs don't say anything about this timeout..)

There are multiple ways to fix this, as I have found:

1. Add `timeout: 30000` to `axios.create` config - this of course doesn't fix the real issue
2. Remove (undefine) `connectTimeout: config.timeout` in the adaptor Promise call when `config.timeout == 0` - this should be the actual fix, I looked at Tauri HTTP plugin Rust source and when the `connectTimeout` is undefined, it doesn't add it to the header configs, which should then rely on default OS settings.

Just making this public in case it is worth fixing, or if anyone has the same problem. Thanks.

**Comment by persiliao** [comment]
The default timeout for axios is 0, and the default timeout for tauri http is also 0. If you don't specify a timeout in axios.create, config.timeout will also be given a default value of 0 when you actually run it into the adapter, so there won't be undefined problem

**Comment by dady8889** [comment]
It is a problem when it is _not_ undefined by default. Default value is _undefined_ in Tauri `fetch`.

Sources:
[JS side](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/http/guest-js/index.ts#L116C9-L116C24)
[Rust side](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/http/src/commands.rs#L224)
https://v2.tauri.app/reference/javascript/http/

**Comment by persiliao** [comment]
This one I have seen, because we are acting as an adapter for axios, which is receiving parameters from axios to build the request

**Comment by persiliao** [comment]
@dady8889 
You're right, I just wrote a demo and tested it, and it does fail to send a request, I'll fix this

**Comment by persiliao** [comment]
It's not only when the timeout is 0 that no request can be made, as long as the timeout is < 1000 no request can be made.

**Comment by persiliao** [comment]
Thanks @dady8889  for spotting this, it's already fixed in 2.0.5
