### ISSUE TITLE
The code 500

### ISSUE THREAD

**Issue by Hodoio** [persiliao/axios-tauri-api-adapter#4]
When my service had a error, the axios was return like this

```json
{
    "status": 200,
    "statusText": "OK",
    "headers": {
        "cache-control": "no-cache",
        "connection": "close",
        "content-encoding": "gzip",
        "content-language": "zh-CN",
        "content-type": "text/html;charset=UTF-8",
        "date": "Thu, 27 Oct 2022 00:46:17 GMT",
        "expires": "0",
        "pragma": "no-cache",
        "server": "nginx",
        "set-cookie": "JSESSIONID=FFAD760EFD7B0A6FD90CB6123892D537; Path=/; HttpOnly",
        "vary": "Accept-Encoding",
        "x-content-type-options": "nosniff",
        "x-frame-options": "SAMEORIGIN",
        "x-xss-protection": "1; mode=block"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 60000,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {
            "FormData": null
        },
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json"
        },
        "method": "post",
        "url": "xxxxxxx",
        "data": "{\"username\":\"sdfsd\",\"password\":\"7d70663568cac5af684503681e3a4d41\"}"
    },
    "request": {}
}
```

My code

```js
import Axios from 'axios'
import AxiosTauriApiAdapter from 'axios-tauri-adapter'

/*
* Axios.create
* @Detail new Axios
**/
let axios = Axios.create({
    timeout: 60000,
    adapter: AxiosTauriApiAdapter
})


export default axios
```

```js
login(form) {
    const data = {
         username: form.username,
         password: md5(form.password)
    }
    return axios.post(`xxxxxx`, data)
}
```

So that is code 500 return data is undefined ? And 400 ？

**Comment by Hodoio** [comment]
Ow, i find error, but it is a new problem for me
I use fetch from @tauri-app/api/http is not this problem
```text
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.invokeGetter (<anonymous>:3:28)
```

**Comment by yangjunPrivate** [comment]
i have a same problem,the reponse status is 200,but the response missing body or return nuthing ,and no error message
mycode like this:
![image](https://user-images.githubusercontent.com/31790089/198494471-fb10738f-91d3-4561-bf75-fdfc1fabe4c6.png)

i can conform the http request can return some test message. when i send the http request ,i alse can conform that the request send to http server,http server returned a json result

**Comment by yangjunPrivate** [comment]
when i user 'axios-tauri-adapter' ,the request returned result just like this:(but the response missing body data):
![image](https://user-images.githubusercontent.com/31790089/198495006-04d6974d-28c9-4045-ae52-172b017dabca.png)

when i use 'axios-tauri-api-adapter' the http request return nothing

**Comment by Hodoio** [comment]
> i have a same problem,the reponse status is 200,but the response missing body or return nuthing ,and no error message mycode like this: ![image](https://user-images.githubusercontent.com/31790089/198494471-fb10738f-91d3-4561-bf75-fdfc1fabe4c6.png)
> 
> i can conform the http request can return some test message. when i send the http request ,i alse can conform that the request send to http server,http server returned a json result

you can use this

```js
import axiosTauriApiAdapter from "axios-tauri-api-adapter"
```
